version: "3.8"
services:

  # Redis
  redis:
    image: redis:alpine
    container_name: redis

  # Database Postgres
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=insurance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=siyamak1981
     
    ports:
      - "5432:5432"
    container_name: postgres_db

  # Django Application
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=siyamak1981
    depends_on:
      - db 
      
  # Celery
  celery:
    restart: always
    build:
      context: .
    command: celery -A insurance worker -l DEBUG 
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app


