# Generated by Django 4.0.1 on 2022-04-17 10:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='TicketEnvelope',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=128)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('description', models.TextField(max_length=1000, verbose_name='Message')),
                ('status', models.CharField(blank=True, choices=[('Backlog', 'Backlog'), ('Waiting On Submitter', 'Waiting On Submitter'), ('In Progress', 'In Progress'), ('Waiting On Support', 'Waiting On Support')], max_length=40, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='tickets.department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_envelop_user', to=settings.AUTH_USER_MODEL, verbose_name='TicketEnvelopUser')),
            ],
            options={
                'verbose_name': 'TicketEnvelop',
                'verbose_name_plural': 'TicketsEnvelops',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TicketLetter',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(max_length=1000, verbose_name='Message')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_reply', to='tickets.ticketenvelope', verbose_name='Reply')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticketenvelope', verbose_name='Ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_letter_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TicketLetters',
                'verbose_name_plural': 'TicketLetters',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('attachment', models.FileField(help_text='supported file: doc, pdf, jpg, png and docx', upload_to='tickets', validators=[django.core.validators.FileExtensionValidator(['docx', 'doc', 'pdf', 'png', 'gepg', 'jpg'])])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketenvelope')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
    ]
