# Generated by Django 4.0.1 on 2022-04-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketenvelope'),
        ),
        migrations.AlterField(
            model_name='ticketenvelope',
            name='status',
            field=models.CharField(blank=True, choices=[('Backlog', 'Backlog'), ('Waiting On Submitter', 'Waiting On Submitter'), ('Progress', 'Progress'), ('Done', 'Done')], max_length=40, null=True),
        ),
    ]
