# Generated by Django 4.0.1 on 2022-04-23 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_alter_attachment_ticket_alter_ticketenvelope_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketenvelope',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_envelop_user', to=settings.AUTH_USER_MODEL, verbose_name='Ticket to'),
        ),
    ]
